
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  sensor:
    - name: "Thread Sensor Temp"
      state_topic: "thread/sensor"
      suggested_display_precision: 1
      unit_of_measurement: "C"
      value_template: "{{ value_json.temp }}"
    - name: "Thread Sensor Humidity"
      state_topic: "thread/sensor"
      unit_of_measurement: "%"
      value_template: "{{ value_json.humid }}"
    - name: "Raw Thread Sensor MQTT"
      state_topic: "thread/sensor"
